#pragma once
/**
 * @file web_search.h
 * @brief Offline-only web search — delegates all queries to the local browser
 * 
 * VISION AI is fully offline. When the user asks to "search" something,
 * we open the query in their local browser instead of making HTTP requests.
 * No outbound network traffic is generated by this module.
 */

#include <string>
#include <functional>
#include <nlohmann/json.hpp>

namespace vision {

class WebSearch {
public:
    /// Callback type: void(query, browser)
    using BrowserSearchFn = std::function<void(const std::string&, const std::string&)>;

    WebSearch() = default;

    /// Set the callback that opens a search in the local browser
    void setBrowserSearchCallback(BrowserSearchFn fn) { browser_search_ = std::move(fn); }

    /// "Search" by opening the query in the user's browser
    nlohmann::json search(const std::string& query);

    /// Returns a message telling the user the search was opened in their browser
    std::string quickAnswer(const std::string& query);

    /// URL-encode a string (utility, kept for other modules)
    static std::string urlEncode(const std::string& text);

private:
    BrowserSearchFn browser_search_;
    std::string default_browser_ = "edge";
};

} // namespace vision
